# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a7c4a0bf3a6cdc530eb76c66cb97b0f58fdb71ab7080d98c229929a2271e189d626f9af938fd832e6c51affaf33bcd647eb2b1bc4cbf494d43729a2c84bed1b

test:
  secret_key_base: ff4c65268400bc2d75acc9317a6d96b9d82e120acdf8e7a29b730d98d0d227ffdfbd377d487489c4cccf9e2edc8e9ae838591b7f5fc6a7aaf2498013ab107dc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
